### PR TITLE
fix lens name, hide unrevealed and collected

### LINKED ISSUE #1: Clipping through undiscovered hexes
Kind of cheat-y
Image

### PR DESCRIPTION
**Pull request by adamk33n3r**
I mentioned a couple of these issues in my review on civ fanatics, but I decided to take a stab at fixing them myself to familiarize with modding Civ 7 as it might be something I'd be interested in.

Fixes #1

### CODE REVIEW

File: discovery-lens/modules/ui/lenses/layer/discovery-layer.js [hunk 1]
```diff
@@ -42,15 +42,16 @@ class DiscoveryLensLayer {
         this.clearOverlay();
     }
     hasDiscovery(plotX, plotY) {
-        const constructibles = MapConstructibles.getConstructibles(plotX, plotY);
+        const constructibles = MapConstructibles.getHiddenFilteredConstructibles(plotX, plotY);
```
Comment (adamk33n3r) [inline discovery-lens/modules/ui/lenses/layer/discovery-layer.js:49]: This function will not return the discovery constructible if you have collected it, so if we use this then it will prevent hexes from highlighting that don't have them anymore

File: discovery-lens/modules/ui/lenses/layer/discovery-layer.js [hunk 2]
```diff
@@ -42,7 +42,11 @@ class DiscoveryLensLayer {
         this.clearOverlay();
     }
     hasDiscovery(plotX, plotY) {
-        const constructibles = MapConstructibles.getConstructibles(plotX, plotY);
+        const isHidden = GameplayMap.getRevealedState(GameContext.localPlayerID, plotX, plotY) == RevealedStates.HIDDEN;
```
Comment (adamk33n3r) [inline discovery-lens/modules/ui/lenses/layer/discovery-layer.js:45]: Don't highlight if the hex has not yet been revealed

File: discovery-lens/modules/l10n/UIText.xml [hunk 3]
```diff
@@ -0,0 +1,8 @@
+﻿<?xml version="1.0" encoding="utf-8"?>
+<Database>
+  <LocalizedText>
+    <Replace Tag="LOC_HOF_CATEGORY_DISCOVERY" Language="zh_Hans_CN">
+        <Text>发现</Text>
```
Comment (adamk33n3r) [inline discovery-lens/modules/l10n/UIText.xml:5]: I am not familiar with Chinese, so I hope this is accurate.

File: discovery-lens/modules/ui/lenses/layer/discovery-layer.js (hunk 1 above)
Comment (hanweizhang) [reply discovery-lens/modules/ui/lenses/layer/discovery-layer.js:49]: Interesting, in my testing, the hexes will not be highlighted after they've been collected. What kind of discovery is it and which environment are you playing under? But good to take this change anyways. Thank you.

Comment (hanweizhang) [reply discovery-lens/modules/ui/lenses/layer/discovery-layer.js:49]: > This function will not return the discovery constructible if you have collected it, so if we use this then it will prevent hexes from highlighting that don't have them anymore

Interesting, in my testing, the hexes will not be highlighted after they've been collected, at least in the first age. What kind of discovery is it and which environment are you playing under? But it's good to take this change anyways. Thank you!

File: discovery-lens/modules/text/en_us/UIText.xml [hunk 4]
```diff
@@ -0,0 +1,9 @@
+
+<?xml version="1.0" encoding="utf-8"?>
+<Database>
+    <EnglishText>
+        <Row Tag="LOC_HOF_CATEGORY_DISCOVERY">
```
Comment (hanweizhang) [inline discovery-lens/modules/text/en_us/UIText.xml:5]: I'm not introducing a new text here. I'm reusing an existing text from the game so that I don't have to provide translation for all locales. It is under "Base/modules/base-standard/text/en_us/HallOfFameText.xml". I'm not sure why the text doesn't show for you... which environment are you playing under? I'm thinking this might be a core game's issue?

File: discovery-lens/modules/ui/lenses/layer/discovery-layer.js (hunk 2 above)
Comment (hanweizhang) [reply discovery-lens/modules/ui/lenses/layer/discovery-layer.js:45]: > Don't highlight if the hex has not yet been revealed

Thanks for catching. I was debating if I wanted to add this check. Continent lens layer has it but many other lens layer like resource lens layer doesn't. So I was assuming the game core is able to handle hidden hexes/plots gracefully lol.

**Review by hanweizhang — APPROVED** [review]
I'm gonna merge it but leave a question mark for the texts for now. IMO it shouldn't be needed. Thanks for your support!

File: discovery-lens/modules/ui/lenses/layer/discovery-layer.js (hunk 1 above)
Comment (adamk33n3r) [reply discovery-lens/modules/ui/lenses/layer/discovery-layer.js:49]: Oh interesting, I was testing it out in the exploration age so maybe it's different there? Every discovery that I had found previously was being highlighted.

File: discovery-lens/modules/text/en_us/UIText.xml (hunk 4 above)
Comment (adamk33n3r) [reply discovery-lens/modules/text/en_us/UIText.xml:5]: Oh I just saw this comment...that's interesting. I'm playing on Steam Windows 11 (if that's what you're asking). You're right though, I see that text in that file. I wonder why it wasn't loading for me. Sorry I didn't search for it in the base game.
